title:       "Alex Limi"
description: "Alex Limi — on Product & Design"
url:         http://limi.net
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: rouge

permalink:     /:title
paginate_path: 'page:num'
paginate:      20

markdown:      kramdown
markdown_ext:  md

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

inc:
  title:        "&#x1D40B;&#x1D408;&#x1D40C;&#x1D408;"
  cover_image:  mountains.jpg
  logo:         logo.png
