inc:
  # Blog Information
  title:        "&#x1D40B;&#x1D408;&#x1D40C;&#x1D408;"
  subtitle:     ""
  cover_image:  mountains.jpg
  logo:         logo.png

url:         http://limi.net
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: true

permalink:     /:title
paginate_path: 'page:num'
paginate:      20

markdown:      kramdown
markdown_ext:  md

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins: 
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false